{{- include "navidrome.validate" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "navidrome.fullname" . }}
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "navidrome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "navidrome.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        fsGroup: {{ .Values.gid }}
      containers:
        - name: navidrome
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.config.enabled }}
          args:
            - -c
            - /navidrome.toml
          {{- end }}
          env:
            - name: ND_DATAFOLDER
              value: /data
            - name: ND_PORT
              value: {{ .Values.service.port | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: navidrome
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: {{ .Values.uid }}
            runAsGroup: {{ .Values.gid }}
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            httpGet:
              path: /
              port: navidrome
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: navidrome
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: navidrome
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.config.enabled }}
            - name: config
              mountPath: /navidrome.toml
              subPath: navidrome.toml
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "navidrome.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.config.enabled }}
        - name: config
          configMap:
            name: {{ include "navidrome.fullname" . }}-config
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
