{{- include "audiobookshelf.validate" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audiobookshelf.fullname" . }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "audiobookshelf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "audiobookshelf.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        fsGroup: {{ .Values.gid }}
      containers:
        - name: audiobookshelf
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: audiobookshelf
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            privileged: false
            runAsUser: {{ .Values.uid }}
            runAsGroup: {{ .Values.gid }}
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            httpGet:
              path: /
              port: audiobookshelf
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: audiobookshelf
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: audiobookshelf
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "audiobookshelf.fullname" . }}-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: metadata
          {{- if .Values.persistence.metadata.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "audiobookshelf.fullname" . }}-metadata
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
