{{- if not .Values.pihole.web.apiPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}-secret
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.pihole.web.apiPassword | b64enc | quote }}
{{- end }}
